(function(){
 'use strict';
 const C=window.NEO_DESKTOP_CONFIG,K='neo_desktop_skins_v1',clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
 let skins=[];try{skins=JSON.parse(localStorage.getItem(K)||'[]');if(!Array.isArray(skins))skins=[];}catch(_){}
 let layer,active=null,raf=0,media={},battery=null,quota=null,connection={status:'checking',label:'Checking connection',summary:'Testing NEO OS services…',ready:0,total:5,latency:0};const nodes=new Map(),weatherRequests=new Map(),equalizerSources=new Map(),failedArtwork=new Set(),WEATHER_TTL=15*60*1000,EQUALIZER_BANDS=32;let equalizerTargets=Array(EQUALIZER_BANDS).fill(0),equalizerValues=Array(EQUALIZER_BANDS).fill(0),equalizerPeaks=Array(EQUALIZER_BANDS).fill(0),equalizerFrame=0,equalizerMeasured=false,equalizerActive=false;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const mediaIcon=name=>{const paths={previous:'<path d="M6 5v14"/><path d="m18 6-9 6 9 6z"/>',play:'<path d="m8 5.5 10 6.5-10 6.5z"/>',pause:'<path d="M9 5v14M15 5v14"/>',next:'<path d="M18 5v14"/><path d="m6 6 9 6-9 6z"/>'};return '<svg class="skin-media-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'+paths[name]+'</svg>';};
 const artworkIcon=()=>'<svg class="skin-media-artwork-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l10-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></svg>';
 function mediaArtwork(){const raw=String(media.cover||'').trim();let cover='';if(raw&&!failedArtwork.has(raw)){try{const url=new URL(raw,location.href);if(['https:','http:','blob:'].includes(url.protocol)||url.protocol==='data:'&&/^data:image\//i.test(raw))cover=url.href;}catch(_){}}return '<span class="skin-media-artwork" aria-hidden="true">'+artworkIcon()+(cover?'<img class="skin-media-cover" src="'+esc(cover)+'" data-cover="'+esc(raw)+'" alt="" decoding="async">':'')+'</span>';}
 const finite=value=>Number.isFinite(Number(value))?Number(value):null;
 function normalizeLevels(values){const source=Array.isArray(values)?values.map(value=>clamp(value,0,1)):[];if(!source.length)return Array(EQUALIZER_BANDS).fill(0);if(source.length===1)return Array(EQUALIZER_BANDS).fill(source[0]);return Array.from({length:EQUALIZER_BANDS},(_,index)=>{const point=index/(EQUALIZER_BANDS-1)*(source.length-1),before=Math.floor(point),after=Math.min(source.length-1,Math.ceil(point)),mix=point-before;return source[before]+(source[after]-source[before])*mix;});}
 function masterOutputGain(){const state=window.NEO_SYSTEM_BRIDGE?.get?.()||{};return state.muted?0:clamp(state.volume===undefined?1:state.volume/100,0,1);}
 function equalizerLevel(value,gain){return Math.min(.94,Math.pow(clamp(value,0,1),1.12)*.98*clamp(gain,0,1));}
 function refreshEqualizerSources(){const now=Date.now(),mixed=Array(EQUALIZER_BANDS).fill(0),masterGain=masterOutputGain();let activeSource=false,measuredSource=false;equalizerSources.forEach((entry,source)=>{if(now-entry.updatedAt>1600){equalizerSources.delete(source);return;}if(entry.active!==true||now-entry.updatedAt>800)return;const sourceGain=masterGain*(entry.muted?0:entry.volume===undefined?1:entry.volume);activeSource=true;measuredSource=measuredSource||entry.measured===true;for(let index=0;index<EQUALIZER_BANDS;index++)mixed[index]=Math.max(mixed[index],equalizerLevel(entry.levels[index]||0,sourceGain));});equalizerTargets=mixed;equalizerActive=activeSource;equalizerMeasured=measuredSource;startEqualizer();}
 function equalizerMotionReduced(){return window.NEO_SYSTEM_BRIDGE?.get().reducedMotion||document.documentElement.dataset.desktopMotion==='reduced'||document.documentElement.dataset.performanceMode==='ultimate'||document.documentElement.classList.contains('is-window-interacting');}
 function updateEqualizers(){equalizerFrame=0;const playing=equalizerActive&&!equalizerMotionReduced();let moving=false,peakLevel=0;for(let index=0;index<EQUALIZER_BANDS;index++){const target=playing?equalizerTargets[index]:0,current=equalizerValues[index],speed=target>current?0.78:0.26,next=current+(target-current)*speed;equalizerValues[index]=next<.002?0:next;equalizerPeaks[index]=Math.max(equalizerValues[index],equalizerPeaks[index]-(playing?0.018:0.055));if(equalizerValues[index]>.003||equalizerPeaks[index]>.003)moving=true;if(equalizerValues[index]>peakLevel)peakLevel=equalizerValues[index];}skins.filter(s=>s.type==='equalizer'&&!s.hidden).forEach(s=>{const node=nodes.get(s.id);if(!node)return;node.classList.toggle('is-equalizer-playing',playing);node.querySelectorAll('.skin-bars i').forEach((bar,index)=>{bar.style.setProperty('--level',(equalizerValues[index]*100).toFixed(1)+'%');bar.style.setProperty('--peak',(equalizerPeaks[index]*100).toFixed(1)+'%');});const status=node.querySelector('[data-equalizer-state]'),energy=node.querySelector('[data-equalizer-energy]');if(status)status.textContent=playing?(equalizerMeasured?'Live audio':'Playback reactive'):'Waiting for audio';if(energy)energy.textContent=playing?Math.round(peakLevel*100)+'%':'32 bands';});if((playing||moving)&&skins.some(s=>s.type==='equalizer'&&!s.hidden))equalizerFrame=requestAnimationFrame(updateEqualizers);}
 function startEqualizer(){if(!equalizerFrame&&skins.some(s=>s.type==='equalizer'&&!s.hidden))equalizerFrame=requestAnimationFrame(updateEqualizers);}
 function normalizeWeather(value){if(!value||typeof value!=='object'||!value.location||!value.current)return null;return {zip:String(value.zip||'').slice(0,5),location:{name:String(value.location.name||'').slice(0,100),region:String(value.location.region||'').slice(0,100),country:String(value.location.country||'US').slice(0,2),timezone:String(value.location.timezone||'').slice(0,80)},current:{temperature:finite(value.current.temperature),apparentTemperature:finite(value.current.apparentTemperature),humidity:finite(value.current.humidity),weatherCode:finite(value.current.weatherCode),isDay:finite(value.current.isDay),precipitation:finite(value.current.precipitation),windSpeed:finite(value.current.windSpeed),windDirection:finite(value.current.windDirection),windGusts:finite(value.current.windGusts),observedAt:String(value.current.observedAt||'').slice(0,40)},today:{high:finite(value.today?.high),low:finite(value.today?.low),precipitationChance:finite(value.today?.precipitationChance)},fetchedAt:finite(value.fetchedAt)||Date.now(),stale:value.stale===true};}
 function save(){try{localStorage.setItem(K,JSON.stringify(skins));window.dispatchEvent(new Event('neo-skins-changed'));}catch(_){window.NEO_SHELL?.notify('Storage full','Widget changes could not be saved.');}}
 function normalize(s,i){const weatherZip=/^\d{5}$/.test(String(s.weatherZip||''))?String(s.weatherZip):'';return {id:String(s.id||'skin-'+i),type:C.skinTypes.includes(s.type)?s.type:'clock',style:C.skinStyles.includes(s.style)?s.style:'minimalist',x:clamp(s.x,8,Math.max(8,innerWidth-180)),y:clamp(s.y,8,Math.max(8,innerHeight-110)),width:clamp(s.width||260,160,Math.max(160,innerWidth-16)),height:clamp(s.height||150,100,Math.max(100,innerHeight-16)),hidden:s.hidden===true,locked:s.locked===true,color:/^#[0-9a-f]{6}$/i.test(s.color)?s.color:'#f1f3f7',backgroundMode:['transparent','color','liquid-glass'].includes(s.backgroundMode)?s.backgroundMode:'liquid-glass',backgroundColor:/^#[0-9a-f]{6}$/i.test(s.backgroundColor)?s.backgroundColor:'#15191f',opacity:clamp(s.opacity??100,35,100),font:['system-ui','monospace','serif'].includes(s.font)?s.font:'system-ui',scale:clamp(s.scale||100,70,300),border:s.border!==false,outline:s.outline===true,shadow:s.shadow===true,z:clamp(s.z||i+1,1,900),text:String(s.text||'').slice(0,5000),weatherZip,weatherData:normalizeWeather(s.weatherData),weatherUpdatedAt:finite(s.weatherUpdatedAt)||0,weatherError:String(s.weatherError||'').slice(0,180),weatherLoading:false};}
 function weatherDescription(code){code=Number(code);if(code===0)return'Clear';if(code===1)return'Mostly clear';if(code===2)return'Partly cloudy';if(code===3)return'Overcast';if(code===45||code===48)return'Fog';if(code>=51&&code<=57)return'Drizzle';if(code>=61&&code<=67)return'Rain';if(code>=71&&code<=77)return'Snow';if(code>=80&&code<=82)return'Showers';if(code===85||code===86)return'Snow showers';if(code>=95)return'Thunderstorms';return'Current conditions';}
 function weatherIcon(code,isDay){code=Number(code);if(code===0)return Number(isDay)===0?'☾':'☀';if(code<=2)return'◒';if(code===3||code===45||code===48)return'☁';if(code>=71&&code<=77||code===85||code===86)return'❄';if(code>=95)return'ϟ';return'☂';}
 function weatherEndpoint(zip){const fallback='http://127.0.0.1:3092/neo-os/',base=location.protocol==='file:'?(window.NEO_LOCAL_CONFIG?.preview||fallback):location.href;const url=new URL('/.netlify/functions/neo-weather',base);url.searchParams.set('zip',zip);return url.href;}
 async function refreshWeather(s,force=false){if(!s||s.type!=='weather'||!s.weatherZip)return;if(!force&&s.weatherData&&Date.now()-s.weatherUpdatedAt<WEATHER_TTL)return;if(weatherRequests.has(s.id))return weatherRequests.get(s.id);s.weatherLoading=true;s.weatherError='';renderContent(s);const request=(async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18_000);try{const response=await fetch(weatherEndpoint(s.weatherZip),{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Live weather is unavailable right now.');const weather=normalizeWeather(payload);if(!weather)throw new Error('The weather service returned an incomplete update.');s.weatherData=weather;s.weatherUpdatedAt=weather.fetchedAt||Date.now();s.weatherError='';}catch(error){s.weatherError=error?.name==='AbortError'?'Weather lookup timed out. Try again.':String(error?.message||'Live weather is unavailable right now.').slice(0,180);}finally{clearTimeout(timer);s.weatherLoading=false;weatherRequests.delete(s.id);renderContent(s);save();}})();weatherRequests.set(s.id,request);return request;}
 function layout(s,n){s.width=Math.min(s.width,innerWidth-16);s.height=Math.min(s.height,innerHeight-16);s.x=clamp(s.x,8,Math.max(8,innerWidth-s.width-8));s.y=clamp(s.y,8,Math.max(8,innerHeight-s.height-8));Object.assign(n.style,{left:s.x+'px',top:s.y+'px',width:s.width+'px',height:s.height+'px',opacity:s.opacity/100,zIndex:s.z,borderWidth:s.border?'1px':'0'});n.style.setProperty('--skin-color',s.color==='#f1f3f7'&&s.style==='minimalist'?'var(--desktop-text)':s.color);n.style.setProperty('--skin-background',s.backgroundColor);n.style.setProperty('--skin-font',s.font);n.style.setProperty('--skin-scale',s.scale/100);n.style.setProperty('--skin-shadow',s.shadow?'0 10px 25px #0007':'0 0 0 transparent');n.dataset.style=s.style;n.dataset.backgroundMode=s.backgroundMode;n.dataset.locked=s.locked;n.dataset.outline=s.outline;n.hidden=s.hidden;}
 function body(s){const now=new Date(),time=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),date=now.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'});switch(s.type){
 case'clock':return '<strong>'+time+'</strong><small>'+date+'</small>';
 case'calendar':return '<strong>'+now.getDate()+'</strong><small>'+date+'</small><p>'+new Date(now.getFullYear(),now.getMonth(),1).toLocaleDateString([],{month:'long',year:'numeric'})+'</p>';
 case'system':return '<strong>NEO OS</strong><small>Local workspace · '+document.querySelectorAll('.neo-window').length+' windows</small><small>'+navigator.hardwareConcurrency+' logical CPU cores reported</small>';
 case'cpu':return '<strong>CPU</strong><small>Live CPU usage is not exposed by the browser.</small><small>'+navigator.hardwareConcurrency+' logical cores reported</small>';
 case'ram':return '<strong>'+(performance.memory?Math.round(performance.memory.usedJSHeapSize/1048576)+' MB':'Unavailable')+'</strong><small>JavaScript heap only · not system RAM</small>';
 case'storage':return '<strong>'+(quota?Math.round(quota.usage/1048576)+' MB':'Checking…')+'</strong><small>Origin storage usage · not disk capacity</small>';
 case'network':return '<strong>'+esc(connection.label||'Checking connection')+'</strong><small>'+esc(connection.summary||'Testing NEO OS services…')+'</small><small>'+esc((connection.ready||0)+' of '+(connection.total||5)+' services ready'+(connection.latency?' · '+connection.latency+' ms':''))+'</small><button data-connection-test aria-label="Test all NEO connections">Retest</button>';
 case'music':{const toggle=media.playing?'pause':'play',toggleLabel=media.playing?'Pause':'Play';return '<div class="skin-media-now">'+mediaArtwork()+'<span class="skin-media-copy"><b>'+esc(media.title||'Nothing playing')+'</b><small>'+esc(media.subtitle||media.artist||'Open Music to listen')+'</small></span></div><div class="skin-media-controls" role="group" aria-label="Music controls"><button class="skin-media-control" data-music="previous" aria-label="Previous song" title="Previous">'+mediaIcon('previous')+'</button><button class="skin-media-control skin-media-toggle" data-music="toggle" aria-label="'+toggleLabel+'" title="'+toggleLabel+'">'+mediaIcon(toggle)+'</button><button class="skin-media-control" data-music="next" aria-label="Next song" title="Next">'+mediaIcon('next')+'</button></div>';}
 case'weather':{if(!s.weatherZip)return '<div class="skin-weather skin-weather-setup"><strong>Set your weather</strong><small>Enter a U.S. ZIP code for live local conditions.</small><form data-weather-setup><input name="zip" inputmode="numeric" autocomplete="postal-code" maxlength="10" pattern="[0-9]{5}(-[0-9]{4})?" placeholder="ZIP code" aria-label="U.S. ZIP code" required><button type="submit">Get weather</button></form>'+(s.weatherError?'<small class="skin-weather-error" role="alert">'+esc(s.weatherError)+'</small>':'')+'</div>';const w=s.weatherData,c=w?.current||{},today=w?.today||{},place=[w?.location?.name,w?.location?.region].filter(Boolean).join(', ');if(!w)return '<div class="skin-weather"><strong>'+(s.weatherLoading?'Finding weather…':'Weather unavailable')+'</strong><small>'+esc(s.weatherError||'No forecast has been loaded for '+s.weatherZip+'.')+'</small><div class="skin-weather-actions"><button data-weather-action="refresh">'+(s.weatherLoading?'Loading…':'Try again')+'</button><button data-weather-action="change">Change ZIP</button></div></div>';const temp=c.temperature===null?'—':Math.round(c.temperature)+'°',feels=c.apparentTemperature===null?'—':Math.round(c.apparentTemperature)+'°',high=today.high===null?'—':Math.round(today.high)+'°',low=today.low===null?'—':Math.round(today.low)+'°',wind=c.windSpeed===null?'—':Math.round(c.windSpeed)+' mph',updated=new Date(s.weatherUpdatedAt||w.fetchedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return '<div class="skin-weather" aria-live="polite"><div class="skin-weather-current"><div><strong>'+temp+'</strong><small>'+esc(weatherDescription(c.weatherCode))+' · '+esc(place||s.weatherZip)+'</small></div><span aria-hidden="true">'+weatherIcon(c.weatherCode,c.isDay)+'</span></div><div class="skin-weather-details"><span>Feels '+feels+'</span><span>H '+high+' / L '+low+'</span><span>Wind '+wind+'</span></div><div class="skin-weather-actions"><small>'+(s.weatherError?'Saved forecast · '+esc(s.weatherError):(w.stale?'Saved forecast':'Updated '+esc(updated)))+'</small><button data-weather-action="refresh" aria-label="Refresh weather">'+(s.weatherLoading?'…':'↻')+'</button><button data-weather-action="change">ZIP</button></div></div>';}
 case'notes':return '<textarea aria-label="Widget note" placeholder="Write a note…">'+esc(s.text)+'</textarea>';
 case'battery':return '<strong>'+(battery?Math.round(battery.level*100)+'%':'Unavailable')+'</strong><small>'+(battery?(battery.charging?'Charging':'On battery'):'Battery details are not exposed here.')+'</small>';
 case'quote':return '<p>'+esc(s.text||['Make room for what matters.','One thing at a time.','Create something worth keeping.'][now.getDate()%3])+'</p>';
 case'equalizer':return '<div class="skin-equalizer" data-equalizer role="img" aria-label="32-band sound equalizer"><div class="skin-bars" aria-hidden="true">'+Array.from({length:EQUALIZER_BANDS},()=>'<i><b></b></i>').join('')+'</div><div class="skin-equalizer-status"><small data-equalizer-state>'+(equalizerActive?(equalizerMeasured?'Live audio':'Playback reactive'):'Waiting for audio')+'</small><span data-equalizer-energy>32 bands</span></div></div>';
 case'launcher':return ['browser','zones','stream','chat','terminal','vscode'].map(id=>'<button data-launch="'+id+'">'+esc(({zones:'Games',stream:'Music',vscode:'Code'})[id]||id)+'</button>').join('');
 }}
 function renderContent(s){const n=nodes.get(s.id);if(!n||s.hidden||n.contains(document.activeElement)&&s.type==='notes')return;n.querySelector('.skin-content').innerHTML=body(s);if(s.type==='music'){const cover=n.querySelector('.skin-media-cover');cover?.addEventListener('error',()=>{const raw=cover.dataset.cover||'';if(raw){failedArtwork.add(raw);if(failedArtwork.size>24)failedArtwork.delete(failedArtwork.values().next().value);}cover.remove();},{once:true});}if(s.type==='equalizer')startEqualizer();}
 function add(type,style){const s=normalize({id:crypto.randomUUID(),type,style,x:100+skins.length%5*30,y:100+skins.length%5*30},skins.length);skins.push(s);mount(s);save();return s.id;}
 function mount(s){const n=document.createElement('section');n.className='neo-skin';n.dataset.skinId=s.id;n.dataset.skinType=s.type;n.setAttribute('aria-label',s.type+' widget');n.innerHTML='<header class="skin-handle" tabindex="0" aria-label="Move '+esc(s.type)+' widget"><strong>'+esc(s.type)+'</strong><button data-skin-action="edit" aria-label="Customize widget">⚙</button><button data-skin-action="hide" aria-label="Hide widget">×</button></header><div class="skin-content"></div>'+['n','e','s','w','ne','nw','se','sw'].map(d=>'<button class="skin-resize" data-dir="'+d+'" aria-label="Resize widget '+d+'" tabindex="'+(d==='se'?0:-1)+'"></button>').join('');layer.append(n);nodes.set(s.id,n);layout(s,n);renderContent(s);}
 function guides(x,y){document.querySelectorAll('.skin-guide').forEach(n=>n.remove());if(x!==null){const n=document.createElement('div');n.className='skin-guide x';n.style.left=x+'px';layer.append(n);}if(y!==null){const n=document.createElement('div');n.className='skin-guide y';n.style.top=y+'px';layer.append(n);}}
 function down(e){const n=e.target.closest('.neo-skin');if(!n||e.button!==0||active)return;const s=skins.find(s=>s.id===n.dataset.skinId),handle=e.target.closest('.skin-resize'),interactive=e.target.closest('button,input,textarea,select,a,[contenteditable="true"]'),drag=!interactive?n:null;if(s.locked||(!handle&&!drag))return;e.preventDefault();e.stopImmediatePropagation();s.z=Math.max(...skins.map(s=>s.z),0)+1;active={s,n,pointer:e.pointerId,target:n,x:e.clientX,y:e.clientY,start:{x:s.x,y:s.y,width:s.width,height:s.height},dir:handle?.dataset.dir||''};n.classList.add(handle?'is-resizing':'is-dragging');n.setPointerCapture(e.pointerId);document.documentElement.classList.add('is-resizing-window','is-moving-widget');}
 function move(e){if(!active||e.pointerId!==active.pointer)return;const a=active,{s,start:b}=a,dx=e.clientX-a.x,dy=e.clientY-a.y;let x=b.x,y=b.y,w=b.width,h=b.height;if(a.dir){if(a.dir.includes('e'))w=clamp(b.width+dx,160,innerWidth-b.x-8);if(a.dir.includes('s'))h=clamp(b.height+dy,100,innerHeight-b.y-8);if(a.dir.includes('w')){x=clamp(b.x+dx,8,b.x+b.width-160);w=b.width+b.x-x;}if(a.dir.includes('n')){y=clamp(b.y+dy,8,b.y+b.height-100);h=b.height+b.y-y;}}else{x=clamp(b.x+dx,8,innerWidth-w-8);y=clamp(b.y+dy,8,innerHeight-h-8);let gx=null,gy=null;const xs=[8,innerWidth-w-8,(innerWidth-w)/2,...skins.filter(z=>z!==s&&!z.hidden).map(z=>z.x)],ys=[8,innerHeight-h-8,(innerHeight-h)/2,...skins.filter(z=>z!==s&&!z.hidden).map(z=>z.y)];xs.some(v=>{if(Math.abs(x-v)<9){x=v;gx=v;return true;}});ys.some(v=>{if(Math.abs(y-v)<9){y=v;gy=v;return true;}});guides(gx,gy);}Object.assign(s,{x,y,width:w,height:h});if(!raf)raf=requestAnimationFrame(()=>{raf=0;if(active)layout(active.s,active.n);});}
 function end(e){if(!active||(e?.pointerId!=null&&e.pointerId!==active.pointer))return;const a=active;active=null;if(raf)cancelAnimationFrame(raf);raf=0;layout(a.s,a.n);a.n.classList.remove('is-dragging','is-resizing');if(a.target.hasPointerCapture(a.pointer))a.target.releasePointerCapture(a.pointer);guides(null,null);document.documentElement.classList.remove('is-resizing-window','is-moving-widget');save();}
 function edit(id){const s=skins.find(s=>s.id===id);if(!s)return;const d=document.createElement('dialog');d.className='desktop-palette desktop-app widget-customizer';d.innerHTML='<h2>Customize '+esc(s.type)+'</h2><p class="desktop-note">Changes appear on the desktop instantly.</p><label>Style<select name="style">'+C.skinStyles.map(v=>'<option>'+v+'</option>').join('')+'</select></label><label>Background<select name="backgroundMode"><option value="transparent">Transparent</option><option value="color">Custom color</option><option value="liquid-glass">Liquid glass</option></select></label><label data-background-color>Background color<input name="backgroundColor" type="color"></label><label>Text color<input name="color" type="color"></label><label>Opacity<input name="opacity" type="range" min="35" max="100"></label><label>Font<select name="font"><option>system-ui</option><option>monospace</option><option>serif</option></select></label><label>Text scale<input name="scale" type="range" min="70" max="300" step="5" aria-label="Widget text scale"></label><label>Border<input name="border" type="checkbox"></label><label>Clean outline<input name="outline" type="checkbox"></label><label>Shadow<input name="shadow" type="checkbox"></label><label>Lock position and size<input name="locked" type="checkbox"></label><div class="desktop-row widget-customizer-actions"><button data-action="position">Reset position</button><button data-action="size">Reset size</button><button class="is-danger" data-action="delete">Delete widget</button><button class="is-primary" data-action="done">Done</button></div>';
 const backgroundColorRow=d.querySelector('[data-background-color]'),syncBackgroundControls=()=>{backgroundColorRow.hidden=s.backgroundMode!=='color';};d.querySelectorAll('[name]').forEach(i=>{if(i.type==='checkbox')i.checked=s[i.name];else i.value=s[i.name];i.addEventListener('input',()=>{s[i.name]=i.type==='checkbox'?i.checked:i.type==='range'?Number(i.value):i.value;syncBackgroundControls();layout(s,nodes.get(id));renderContent(s);save();});});syncBackgroundControls();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect(),outside=e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom;if(outside){d.close();return;}}const a=e.target.dataset.action;if(a==='done')d.close();if(a==='position'){s.x=100;s.y=100;}if(a==='size'){s.width=260;s.height=150;}if(a==='delete'){skins=skins.filter(x=>x!==s);nodes.get(id).remove();nodes.delete(id);d.close();}if(a){if(nodes.has(id))layout(s,nodes.get(id));save();}});d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();}
 function init(){
  layer=document.createElement('div');layer.className='skin-layer';layer.id='neo-skins';(document.getElementById('neo-desktop')||document.body).append(layer);skins=skins.map(normalize);skins.forEach(mount);
  layer.addEventListener('pointerdown',down,true);layer.addEventListener('pointermove',move);layer.addEventListener('pointerup',end);layer.addEventListener('pointercancel',end);layer.addEventListener('lostpointercapture',end);window.addEventListener('blur',()=>end());
  layer.addEventListener('keydown',e=>{const n=e.target.closest('.neo-skin'),s=n&&skins.find(s=>s.id===n.dataset.skinId);if(!s||s.locked||!e.key.startsWith('Arrow'))return;if(e.target.closest('.skin-resize')){s.width+=e.key==='ArrowRight'?8:e.key==='ArrowLeft'?-8:0;s.height+=e.key==='ArrowDown'?8:e.key==='ArrowUp'?-8:0;s.width=Math.max(160,s.width);s.height=Math.max(100,s.height);}else if(e.target.classList.contains('skin-handle')){s.x+=e.key==='ArrowRight'?8:e.key==='ArrowLeft'?-8:0;s.y+=e.key==='ArrowDown'?8:e.key==='ArrowUp'?-8:0;}else return;e.preventDefault();layout(s,n);save();});
  layer.addEventListener('input',e=>{if(e.target.matches('textarea')){const s=skins.find(s=>s.id===e.target.closest('.neo-skin').dataset.skinId);s.text=e.target.value.slice(0,5000);save();}});
  layer.addEventListener('submit',e=>{const form=e.target.closest('[data-weather-setup]');if(!form)return;e.preventDefault();const n=form.closest('.neo-skin'),s=n&&skins.find(item=>item.id===n.dataset.skinId),zip=String(new FormData(form).get('zip')||'').trim();if(!s)return;if(!/^\d{5}(?:-\d{4})?$/.test(zip)){s.weatherError='Enter a valid 5-digit U.S. ZIP code.';renderContent(s);return;}s.weatherZip=zip.slice(0,5);s.weatherData=null;s.weatherUpdatedAt=0;s.weatherError='';save();refreshWeather(s,true);});
  layer.addEventListener('click',e=>{const n=e.target.closest('.neo-skin');if(!n)return;const s=skins.find(s=>s.id===n.dataset.skinId),a=e.target.closest('button')?.dataset;if(!a)return;if(a.skinAction==='edit')edit(s.id);if(a.skinAction==='hide'){s.hidden=true;layout(s,n);save();}if(a.launch)window.NEO_SHELL.openApp(a.launch);if(a.music){if(!media.active)window.NEO_SHELL.openApp('stream');else window.dispatchEvent(new CustomEvent('neo-media-transport-request',{detail:{source:media.source,action:a.music}}));}if(a.connectionTest)window.NEO_CONNECTION_MONITOR?.refresh();if(a.weatherAction==='refresh')refreshWeather(s,true);if(a.weatherAction==='change'){s.weatherZip='';s.weatherData=null;s.weatherUpdatedAt=0;s.weatherError='';renderContent(s);save();requestAnimationFrame(()=>nodes.get(s.id)?.querySelector('[name="zip"]')?.focus());}});
  window.addEventListener('neo-media-state',e=>{media=e.detail||{};skins.filter(s=>s.type==='music').forEach(renderContent);const source=String(media.source||'media'),current=equalizerSources.get(source)||{levels:Array(EQUALIZER_BANDS).fill(0),measured:false};equalizerSources.set(source,{levels:current.levels,measured:current.measured,volume:media.volume===undefined?1:clamp(media.volume,0,1),muted:media.muted===true,active:media.active!==false&&media.playing===true,updatedAt:Date.now()});refreshEqualizerSources();});
  window.addEventListener('neo-media-levels',e=>{const detail=e.detail||{},source=String(detail.source||'audio'),levels=normalizeLevels(detail.levels),peak=Math.max(...levels),linked=media.source===source&&media.playing===true,current=equalizerSources.get(source)||{};equalizerSources.set(source,{levels,measured:detail.measured===true,volume:current.volume===undefined?1:current.volume,muted:current.muted===true,active:detail.active===true||(detail.active!==false&&(linked||peak>.006)),updatedAt:Date.now()});refreshEqualizerSources();});
  window.addEventListener('neo-system-state',refreshEqualizerSources);
  window.addEventListener('neo-window-interaction',e=>{if(e.detail?.active===true){if(equalizerFrame)cancelAnimationFrame(equalizerFrame);equalizerFrame=0;}else startEqualizer();});
  window.NEO_CONNECTION_MONITOR?.subscribe(value=>{connection=value||connection;skins.filter(s=>s.type==='network').forEach(renderContent);});
  window.addEventListener('online',()=>skins.filter(s=>s.type==='weather'&&s.weatherZip).forEach(s=>refreshWeather(s)));window.addEventListener('resize',()=>{end();skins.forEach(s=>layout(s,nodes.get(s.id)));save();});navigator.getBattery?.().then(b=>battery=b).catch(()=>{});navigator.storage?.estimate?.().then(v=>quota=v).catch(()=>{});skins.filter(s=>s.type==='weather'&&s.weatherZip).forEach(s=>refreshWeather(s));setInterval(()=>{if(document.hidden)return;skins.filter(s=>!['notes','launcher','weather','quote','equalizer','music'].includes(s.type)).forEach(renderContent);},1000);setInterval(()=>{if(document.hidden)return;refreshEqualizerSources();},300);setInterval(()=>{if(document.hidden)return;skins.filter(s=>s.type==='weather'&&s.weatherZip).forEach(s=>refreshWeather(s));},WEATHER_TTL);
 }
 window.NEO_SKINS={init,add,edit,list:()=>skins.map(s=>({...s})),show:(id,visible=true)=>{const s=skins.find(s=>s.id===id);if(s){s.hidden=!visible;layout(s,nodes.get(id));renderContent(s);save();}}};
})();
